version: '3'

services:
  frontend:
    build: frontend_server/
    depends_on:
      - 'database'
    ports: 
      - '3020:3000'
    stdin_open: true

  backend:
    build: backend_server/
    depends_on:
      - 'database'
    ports:
      - '3021:3001'

  database:
    build: database/
    restart: always
    ports:
      - '5444:5432'